# version: '3.8'

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
    - "8080:80"
    depends_on:
      - wordpress
    volumes:
      - ./web:/var/www/html
  wordpress:
      build: requirements/wordpress/
      container_name: wordpress
      depends_on:
        - mariadb
      environment:
        - WORDPRESS_DB_USER=${MARIADB_USER}
        - WORDPRESS_DB_PASSWORD=${MARIADB_PASSWORD}
        - WORDPRESS_DB_NAME=${MARIADB_DATABASE}
        - WORDPRESS_ADMIN_NAME=${WORDPRESS_ADMIN_NAME}
        - WORDPRESS_ADMIN_PASS=${WORDPRESS_ADMIN_PASS}
        - WORDPRESS_USER_NAME=${WORDPRESS_USER_NAME}
        - WORDPRESS_USER_PASS=${WORDPRESS_USER_PASS}
      volumes:
      - ./web:/var/www/html
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    environment:
    - MARIADB_USER=${MARIADB_USER}
    - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    - MARIADB_DATABASE=${MARIADB_DATABASE}
    - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - /home/ivan-mel/data/mariadb
    networks:
      - inception

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/ivan-mel/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/ivan-mel/data/wordpress
      o : bind
      type : none


networks:
  inception:
    driver: local